# #region - domain redirects
# NOTE: usage of redirecting external domains this way requires also adding each domain to the Netlify dashboard and setting records at the domain registrar to point to Netlify.
# NOTE: an alternate option is to use the domain registrar's "domain redirect" feature, but some don't support `https` redirects (name.com). To work around this, you can point the nameservers to Cloudflare and use their "Page Rules" feature to set up the redirect.
[[redirects]]
from = "https://zachhardesty.netlify.app/*"
to = "https://zachhardesty.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://zachhardesty.me/*"
to = "https://zachhardesty.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.zachhardesty.me/*"
to = "https://zachhardesty.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://zachhardesty.dev/*"
to = "https://zachhardesty.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.zachhardesty.dev/*"
to = "https://zachhardesty.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://hardesty.dev/*"
to = "https://zachhardesty.com/:splat"
status = 302
force = true

[[redirects]]
from = "https://www.hardesty.dev/*"
to = "https://zachhardesty.com/:splat"
status = 302
force = true

[[redirects]]
from = "https://hardesty.consulting/*"
to = "https://zachhardesty.com/:splat"
status = 302
force = true

[[redirects]]
from = "https://www.hardesty.consulting/*"
to = "https://zachhardesty.com/:splat"
status = 302
force = true
# #endregion

# #region - go links
[[redirects]]
from = "https://zachhardesty.com/go/resume/"
to = "https://docs.google.com/document/d/1JluScSVuuTK9wMS2gK6ygd-4tRxCO73tvwR3lvDe1hI"
# endregion

# plugins:
# https://github.com/munter/netlify-plugin-checklinks
# - package: netlify-plugin-checklinks
# - package: netlify-plugin-image-optim
# https://github.com/munter/netlify-plugin-subfont#configuration
# - package: netlify-plugin-subfont
# https://github.com/munter/netlify-plugin-hashfiles
# - package: netlify-plugin-hashfiles
# - package: netlify-plugin-lighthouse
#   config:
#     url: "https://zachhardesty.com"
